{% set name = "sphinx-prompt" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 70c8e66d1f36def1e295ed961c7562bbf8fc697eea5191b92b41e4784c264ef5

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.0
  run:
    - python >=3.0
    - pygments
    - sphinx

about:
  home: https://github.com/sbrunner/sphinx-prompt
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sphinx directive to add unselectable prompt
  doc_url: https://github.com/sbrunner/sphinx-prompt/blob/master/README.rst
  dev_url: https://github.com/sbrunner/sphinx-prompt

extra:
  recipe-maintainers:
    - jonathansick
